### ISSUE TITLE
MacOS : npm install doesn't run npm run update-firmware

### ISSUE THREAD

**Issue by haeferer** [Brewskey/spark-protocol#121]
result: missing directories for flow etc.

Workaround: 
run from commandline
```
npm run update-firmware
```

**Comment by jlkalberer** [comment]
I guess start with a fresh install of spark-protocol and see if it repros.

If not, we'll need to add to the readme about OSX

**Comment by haeferer** [comment]
Already tried, it seems that ```npm install``` completes without an error (first run), but doesnt run the script. After you run ```npm install``` again you will get an error message

Maybe the "afterinstall" script doesnt run as SUDO (even if npm is run as sudo). 
I think it's the same problem like running ```ava``` without ``` --no-cache ``` option

**Comment by AntonPuko** [comment]
if it's `sudo` issue, I guess it's completely user-side problem and we don't have to fix it. I wish I could reproduce it, but i don't have mac :)

**Comment by haeferer** [comment]
I don't think we can fix this problem. There seems to be a problem on first run of NPM install with indirect install scripts (spark-server required sparkprotocoll and spark-Protocol installs using a script ) 

Workaround. Simply run  twice to ensure the script runs
