### ISSUE TITLE
Problem updating Particle with firmware 0.6.0-Photon with App compiled against 0.6.2

### ISSUE THREAD

**Issue by haeferer** [Brewskey/spark-protocol#129]
look at
[https://github.com/Brewskey/spark-server/issues/239](https://github.com/Brewskey/spark-server/issues/239)

**Comment by jlkalberer** [comment]
Why open a duplicate issue...?

**Comment by haeferer** [comment]
I dont know if this is a problem of spark-server or spark-protocol. In future i will always open an issue in spark-server. Sorry
