### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by jinyangqiao** [Brewskey/spark-protocol#134]
when I git the newest [spark-server](https://github.com/Brewskey/spark-server) dev ,
run npm install,at first ,it seems everything is ok,until it comes to **update-firmware**
and **Downloading voodoospark.bin**, something goes wrong like this:

Downloading photon_tinker.bin...
Downloading tinker-usb-debugging-v0.4.8-rc.6-electron.bin...
Downloading voodoospark.bin...
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: connect ETIMEDOUT 151.101.228.133:443
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! spark-server@0.1.1 postinstall: `update-firmware`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spark-server@0.1.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\me\AppData\Roaming\npm-cache\_logs\2018-05-16T10_15_00_098Z-debug.log

**Comment by jinyangqiao** [comment]
sometimes npm install is OK,
but too many times ,It has the above error

**Comment by jlkalberer** [comment]
That looks like a timeout with github when you're downloading the binaries.

Are you located in China? That could be the issue.

**Comment by jinyangqiao** [comment]
Yes,I am in China，
I see, thank you

**Comment by jlkalberer** [comment]
Yeah, I'm not 100% sure that this is the issue but the timeout would make sense. I don't think Github has servers there.

You can get it to work some times correct?

**Comment by jinyangqiao** [comment]
Yes, sometimes it's ok!

**Comment by jlkalberer** [comment]
Ok, I'm going to close this then. There isn't anything we can do :/
