### ISSUE TITLE
support for System.disableUpdates() ?

### ISSUE THREAD

**Issue by DaliborFarny** [Brewskey/spark-protocol#146]
Currently, the spark-protocol doesn't support OTA disable/enable functions on the device. When the OTA updates are disabled via calling System.disableUpdates(), the cloud tries to push OTA update, but fails and drops the connection to the device. The cloud doesn't recognize that the updates are disabled, dropping connections and trying OTA again - happening in a loop until the updates are enabled on the device again via System.enableUpdates().

We would like to disable updates for a couple of minutes after the startup of a device when there is a higher risk that the user will power-off the device again (tinkering with it). While the Photon should theoretically handle this, we've seen several cases (on a 700 devices fleet) when this exact thing resulted in the Photon getting stuck in OTA update - needed a manual flashing of the firmware over USB.

This is output from the cloud when trying to OTA to a device with disabled updates:

`{"name":"Device.js","hostname":"DXXXX","pid":2137,"level":30,"deviceID":"3b002f000147393038000000","msg":"flash device started! - sending api event","time":"2021-04-30T08:26:10.917Z","v":0}
{"name":"Flasher.js","hostname":"DXXXX","pid":2137,"level":30,"cache_key":"_6543","deviceID":"3b002f000147393038000000","msg":"fast ota enabled! ","time":"2021-04-30T08:26:10.917Z","v":0}
{"name":"Device.js","hostname":"DXXXX","pid":2137,"level":30,"cache_key":"_6543","deviceID":"3b002f000147393038000000","duration":5.652,"disconnectCounter":1,"msg":"Device disconnected","time":"2021-04-30T08:26:16.437Z","v":0}
{"name":"DeviceServer.js","hostname":"DXXXX","pid":2137,"level":40,"connectionKey":"_6543","deviceID":"3b002f000147393038000000","ownerID":null,"msg":"Session ended for Device","time":"2021-04-30T08:26:16.438Z","v":0}
{"name":"Device.js","hostname":"DXXXX","pid":2137,"level":30,"deviceID":"3b002f000147393038000000","msg":"Releasing flash ownership","time":"2021-04-30T08:26:16.438Z","v":0}
{"name":"Device.js","hostname":"DXXXX","pid":2137,"level":50,"deviceID":"3b002f000147393038000000","msg":"Flash device failed! - sending api event","time":"2021-04-30T08:26:16.439Z","v":0}
{"name":"DeviceServer.js","hostname":"DXXXX","pid":2137,"level":50,"deviceID":"3b002f000147393038000000","err":{"message":"Cannot read property 'message' of undefined","name":"TypeError","stack":"TypeError: Cannot read property 'message' of undefined\n    at Device._callee9$ (/usr/local/bin/spark-server/node_modules/spark-protocol/dist/clients/Device.js:1017:66)\n    at tryCatch (/usr/local/bin/s                                 park-server/node_modules/regenerator-runtime/runtime.js:62:40)\n    at Generator.invoke [as _invoke] (/usr/local/bin/spark-server/node_modules/regenerator-runtime/runtime.js:296:22)\n    at Generator.prototype.(anonymous function) [as throw] (/usr/local/bin/spark-server/node_modules/regenerator-runtime/runtime.js:114:21)\n    at step (/usr/local/bin/spark-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)\n    at /usr/local/bin/spark-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:30:13\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"msg":"Connection Error","time":"2021-04-30T08:26:16.439Z","v":0}`

**Comment by jlkalberer** [comment]
I don't know if I can support disabling updates because it would add a lot of extra complexity.

I can figure out why the exception is being thrown and fix that -- it might be good enough to fix your issue in the short term.
I'll try to look at this over the weekend.

**Comment by DaliborFarny** [comment]
Thank you, if the cloud doesnt drop the connection because it can't OTA, it will be 100% OK. Interesting is that when I OTA manually, it doesn't drop the connection - only when the OTA is initiated by a firmware update for a device under product.

**Comment by jlkalberer** [comment]
I took a look at the exception this morning. This exception seems to just be a bug in the code generation.
I'll need to update `spark-protocol` and `spark-server` with an updated build to hopefully fix the exception.

That said, it doesn't help with your problem -- we'd just get better logs.
With the better logs I may be able to track down where exactly things are failing. I'm guessing that there is some sort of timeout going on with your devices. I personally don't ever see this issue but I also have a significantly smaller fleet :)

**Comment by DaliborFarny** [comment]
Sounds good, some additional information - this is a log from an attempt to do OTA manually (not via releasing firmware to product).

The cloud behaves correctly, the connection is preserved, the CLI responses with: **Failed to flash 3b002f00014739XXXXXXXXXX: Response timeout for event: spark-server/flash_device**

`[2021-05-07T07:40:57.089Z]  INFO: Device.js/2137 on DXXXX: flash device started! - sending api event (deviceID=3b002f00014739XXXXXXXXXX)
[2021-05-07T07:40:57.090Z]  INFO: Flasher.js/2137 on DXXXX: fast ota enabled!  (cache_key=_17817, deviceID=3b002f00014739XXXXXXXXXX)
[2021-05-07T07:40:57.163Z] ERROR: Device.js/2137 on DXXXX: FOOOOOO
    packet: {
      "code": 5.03,
      "confirmable": false,
      "reset": false,
      "ack": true,
      "messageId": 21157,
      "token": {
        "type": "Buffer",
        "data": [
          5
        ]
      },
      "options": [],
      "payload": {
        "type": "Buffer",
        "data": []
      }
    }
[2021-05-07T07:41:12.165Z]  INFO: Device.js/2137 on DXXXX: Releasing flash ownership (deviceID=3b002f00014739XXXXXXXXXX)
[2021-05-07T07:41:12.165Z] ERROR: Device.js/2137 on DXXXX: Flash device failed! - sending api event (deviceID=3b002f00014739XXXXXXXXXX)
    Error: Request timed out ChunkReceived
        at Timeout._onTimeout (/usr/local/bin/spark-server/node_modules/spark-protocol/dist/clients/Device.js:694:28)
        at ontimeout (timers.js:436:11)
        at tryOnTimeout (timers.js:300:5)
        at listOnTimeout (timers.js:263:5)
        at Timer.processTimers (timers.js:223:10)
`

**Comment by jlkalberer** [comment]
Ahhh... ok, so what I think is happening is that:

1. Device is part of some product
2. Device has a certain version number of the product

When you try to flash with the custom firmware, it's getting clobbered/reverted by the product firmware.
If you build with VERSION_NUMBER+1 and flash that, you shouldn't run into issue when trying to flash.

Generally when I try to flash a device with custom firmware, I remove it from the product and it makes things a lot easier.

Let me know if that works.

**Comment by DaliborFarny** [comment]
Hi!

That particular device is assigned to a test product - I go the same way as I would in the case of a customer's device. I am testing the exact same situation that would happen on a live product. The manual OTA flashing I mentioned was done on a device that was not assigned to any product.

1. I assign the Device under Product
2. I upload new firmware (VERSION_NUMBER+1) to the Product
2. The new FW is set to current:true
3. the Server detects the Device needs to be updated
4. The Device refuses to receive the update, but the Server keeps trying (this is OK) while dropping the connection (not OK)

I guess the manual OTA flash is attempted only once and once refused, it is thrown away. The problem is with the Device being under the Product - the Server will try to flash the device every time the Device reconnects to the cloud and the Server finds out it has a lower firmware version. I think the solution would be to just not drop the connection after unsuccessful flash, but I am not sure whether this can't affect regular OTA updates - there are often timeouts, connection drops etc. during normal OTA.

What I am trying to do - to disable the OTA updates few minutes after the start of the device. At this time, the user often powers cycle the device (especially when seeing it is not doing what it should because of OTA in progress). The Photon should handle this, but in reality it sometimes (rarely) corrupts wifi credentials stored in EEPROM (flash actually), leaving the device in the middle of OTA update without a connection to the internet - so it cant continue in the update.. I also saw corrupted private and/or public keys - unable to connect to the server. All this happened at 0.6.3, never saw it on 1.4.4 which we've been using for a year now.

Thank you for looking at it!

**Comment by DaliborFarny** [comment]
The last commit works 100% issue fixed. Thank you so much!
