### ISSUE TITLE
spark system firmware events filtering

### ISSUE THREAD

**Issue by AntonPuko** [Brewskey/spark-protocol#24]
add filtering inside Device.js for some of those events: https://github.com/spark/firmware/blob/04f35df7a7b0e1bd9df8e6bfce7a3393dfe70861/system/src/system_cloud_internal.cpp#L675-L707
to be able to get private constants like `max_binary` and `ota_chunk_size`

**Comment by jlkalberer** [comment]
I'm actually working on this now in order to get OTA going. I'm probably not going to implement all the events though.
