### ISSUE TITLE
(question) Is this compatible with the Electron as well ? 

### ISSUE THREAD

**Issue by bilics** [Brewskey/spark-protocol#73]
Hi!

Just wondering if this is compatible with the electron as well.

I have been looking at ways to build my own backend (similar to what particle provides) but hosted at AWS. 

I have been reading the discussion here 

https://community.particle.io/t/local-cloud-a-k-a-spark-server-updates/26792/21

as well. 

I understand this project provides OTA, events and functions as does the official/paid particle cloud offers. Is this correct ?

Thanks and sorry if this is not the right place to ask.

**Comment by jlkalberer** [comment]
Hi @bilics,

This should support electron but I haven't tested it yet.  I can't test on my local machine unless I do some dynamic DNS to route the electron.

I'm planning on testing this once I've set up my production server.  That will be at least a few weeks to a month out as I'm currently focused on other aspects of my project.

If you wanted to test and verify that it's working that would be great.

**Comment by bilics** [comment]
Thanks @jlkalberer! I will try to test it on my side.

Should I follow this

https://docs.particle.io/support/troubleshooting/cloud-solutions/photon/

to install the spark-server (this fork) on AWS ?

Thanks again,

**Comment by jlkalberer** [comment]
Just follow the README.md in this repo. What they have *should* work for the most part but we've made some minor tweaks on things.  Feel free to comment here if you get stuck on anything. Any issues you run into should be documented here.

**Comment by jlkalberer** [comment]
Ok, it did some digging and it looks like Electron won't work. 
The Electron uses UDP and a different key style for handling the connections.

Particle has created a server module for this https://github.com/spark/node-mbed-dtls/ but I don't have time to add it to the protocol/server right now.

I don't think it would be too hard to add if you wanted to do a PR.  I've added a new issue here https://github.com/Brewskey/spark-protocol/issues/81

**Comment by durielz** [comment]
I do not have any Electron to test but it seems you can change the protocol using
`particle keys protocol tcp`
and then flash the server key for TCP mode
`particle keys server public_key.der IP_ADDRESS --protocol tcp`
