### ISSUE TITLE
Add setting to prevent automatic system firmware update

### ISSUE THREAD

**Issue by wdimmit** [Brewskey/spark-protocol#83]
It is not always desirable to have devices upgraded to the latest firmware.  A setting to disable this feature would be fantastic.

Thanks.

**Comment by AntonPuko** [comment]
@wdimmit should be fixed after merging these two diffs:
https://github.com/Brewskey/spark-server/pull/128 and 
https://github.com/Brewskey/spark-protocol/pull/84

Notice, that we merge spark-server and spark-protocol settings and spark-server have precedence.
so if you use spark-protocol with our spark-server, you should change ENABLE_SYSTEM_FIRWMARE_AUTOUPDATES there.
