### ISSUE TITLE
Use firmware to get latest system version for updates.

### ISSUE THREAD

**Issue by jlkalberer** [Brewskey/spark-protocol#88]
Right now we use a readme file to figure this out. Let's use the source of truth for the firmware instead.

https://github.com/spark/firmware/blob/develop/system/inc/system_version.h

---

Either that or try one of the other things here:
https://github.com/spark/firmware/pull/1264#issuecomment-287160347

It might make sense to just make a dummy account with an access token to do this :/

**Comment by haeferer** [comment]
this breaks on jun/2017, look #126 , Patch for new readme format is #127

**Comment by jlkalberer** [comment]
I think this is resolved with the newer model for fetching system firmware.
